---
# TODO[VCC-003]: Implement tasks for NFS server setup

# - name: "Create NFS share directory"

# - name: Install NFS server

# - name: Configure exports
#   ansible.builtin.template:
#     src: exports
#     dest: /etc/exports
#   notify: Restart NFS server

# - name: Start NFS server


# 1) Create NFS share directory
- name: Create NFS share directory
  ansible.builtin.file:
    path: "{{ data_dir }}"
    state: directory
    mode: "0777"

# 2) Install NFS server
- name: Install NFS server packages
  ansible.builtin.apt:
    name:
      - nfs-kernel-server
    update_cache: yes
  become: true

# 3) Configure exports using template
- name: Configure exports
  ansible.builtin.template:
    src: exports # Source template file
    dest: /etc/exports # Destination on server
  notify: Restart NFS server # Trigger handler if changed in exports 

# 4) Start NFS server service
- name: Start and enable NFS server
  ansible.builtin.service:
    name: nfs-kernel-server
    state: started
    enabled: yes




## check exports
- block:
  - name: Apply notifiers
    ansible.builtin.meta: flush_handlers
  - name: Get verbose export list
    ansible.builtin.command: exportfs -v
    register: exportfs_verbose
    changed_when: false
  - name: Assert that the export exists with correct options
    ansible.builtin.assert:
      that:
        - exportfs_verbose.stdout is search(storage_network | regex_escape ~ '\\s*\\(.*rw.*no_root_squash.*\\)')
      fail_msg: "Export for {{ storage_network }} is missing or has incorrect options"
  when: enable_asserts
