---
# TODO[VCC-003]: Implement tasks for NFS server setup

# - name: "Create NFS share directory"

# - name: Install NFS server

# - name: Configure exports
#   ansible.builtin.template:
#     src: exports
#     dest: /etc/exports
#   notify: Restart NFS server

# - name: Start NFS server

## check exports
- block:
  - name: Apply notifiers
    ansible.builtin.meta: flush_handlers
  - name: Get verbose export list
    ansible.builtin.command: exportfs -v
    register: exportfs_verbose
    changed_when: false
  - name: Assert that the export exists with correct options
    ansible.builtin.assert:
      that:
        - exportfs_verbose.stdout is search(storage_network | regex_escape ~ '\\s*\\(.*rw.*no_root_squash.*\\)')
      fail_msg: "Export for {{ storage_network }} is missing or has incorrect options"
  when: enable_asserts
