{
 "title": "Grafana Available Resources",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Available",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (host) (\n  rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Available ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "{{ '{{' }}host{{ '}}' }}" }
   ]
  },
  {
   "title": "Disk Available",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (host) (\n  node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay|squashfs\", mountpoint!~\"/run.*|/var/lib/docker.*|/var/lib/containerd.*\"}\n) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network drop",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_drop_total",
     "legendFormat": "{{ '{{' }}host{{ '}}' }} / {{ '{{' }}device{{ '}}' }}"
    }
   ]
  }
 ]
}